// <auto-generated />
using CoreApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190311165321_Initial Domain Seed Data")]
    partial class InitialDomainSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoreApi.Models.AdHocDocumentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DocumentDescription");

                    b.Property<int>("DocumentId");

                    b.Property<string>("DocumentName");

                    b.HasKey("Id");

                    b.ToTable("AdHocDocuments");
                });

            modelBuilder.Entity("CoreApi.Models.DomainModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DomainDescription");

                    b.Property<string>("DomainName");

                    b.HasKey("Id");

                    b.ToTable("Domains");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DomainDescription = "This is the domain of the first dynamic document repository",
                            DomainName = "First Domain"
                        },
                        new
                        {
                            Id = 2,
                            DomainDescription = "This is the domain of the Second dynamic document repository",
                            DomainName = "Second Domain"
                        },
                        new
                        {
                            Id = 3,
                            DomainDescription = "This is the domain of the Third dynamic document repository",
                            DomainName = "Third Domain"
                        },
                        new
                        {
                            Id = 4,
                            DomainDescription = "This is the domain of the Forth dynamic document repository",
                            DomainName = "Forth Domain"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
